#
# Executes commands at login pre-zshrc.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

export TERM=tmux-256color

export EDITOR='nvim'
export VISUAL='nvim'
export PAGER='less'
export SHELL='/bin/zsh'

export LANG='en_US.UTF-8'

export VDPAU_DRIVER=radeonsi

export GOPATH=/project/go
export ANDROID_HOME=${HOME}/Android/Sdk
export NODE_PATH=/usr/bin/node
export RUST_SRC_PATH=~/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src
export JAVA_HOME=/usr/lib/jvm/default
export _JAVA_OPTIONS='-Dawt.useSystemAAFontSettings=on -Dswing.aatext=true -Dswing.defaultlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel -Djdk.gtk.version=3 -Dsun.java2d.opengl=true'
export QT_QPA_PLATFORMTHEME="qt5ct"

#echo $PATH

#export PATH=${PATH}:/usr/bin
#export PATH=${PATH}:/usr/local/bin:/usr/local/sbin
export PATH=${PATH}:~/bin:~/.local/bin:~/.local/sbin
export PATH=${PATH}:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
# export PATH=${PATH}:~/.npm-global/bin
export PATH=${PATH}:${GOPATH}/bin
export PATH=${PATH}:~/scripts
export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools
export PATH=${PATH}:~/.gem/ruby/2.4.0/bin
export PATH=${PATH}:~/git-semantic-commits
#export PATH=${PATH}:~/Downloads/google-cloud-sdk/bin
export PATH=${PATH}:~/.cargo/bin

for i in `ls /usr/share/groovy/lib/ | grep jar`; do
  export CLASSPATH=$CLASSPATH":/usr/share/groovy/lib/"$i
done

# Ensure path arrays do not contain duplicates.
typeset -gU cdpath fpath mailpath path

# Set the list of directories that cd searches.
# cdpath=(
#   $cdpath
# )

# Set the list of directories that Zsh searches for programs.
#path=(
  #/usr/local/{bin,sbin}
  #$path
#)

#
# Less
#

# Set the default Less options.
# Mouse-wheel scrolling has been disabled by -X (disable screen clearing).
# Remove -X and -F (exit if the content fits on one screen) to enable it.
export LESS='-F -g -i -M -R -S -w -X -z-4'

# Set the Less input preprocessor.
# Try both `lesspipe` and `lesspipe.sh` as either might exist on a system.
if (( $#commands[(i)lesspipe(|.sh)] )); then
  export LESSOPEN="| /usr/bin/env $commands[(i)lesspipe(|.sh)] %s 2>&-"
fi

#
# Temporary Files
#

if [[ ! -d "$TMPDIR" ]]; then
  export TMPDIR="$(mktemp -d)"
fi

TMPPREFIX="${TMPDIR%/}/zsh"

source ~/.profile

if [ -z "$DISPLAY" ] && [ -n "$XDG_VTNR" ] && [ "$XDG_VTNR" -eq 1 ]; then
  exec startx
fi
