#
# Executes commands at login pre-zshrc.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

[ -f ~/.profile ] && source ~/.profile

export EDITOR='nvim'
export VISUAL='nvim'
export PAGER='less'
export SHELL='/bin/zsh'

export LANG='en_US.UTF-8'

# export GOPATH=/project/go
export ANDROID_HOME=${HOME}/Library/Android/Sdk
export ANDROID_SDK_ROOT=$ANDROID_HOME
export NODE_PATH=$(npm -g root)
# export RUST_SRC_PATH=~/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src
export JAVA_HOME=`/usr/libexec/java_home`

export PATH=${PATH}:~/scripts
export PATH=${PATH}:~/git-semantic-commit
export PATH=${PATH}:`yarn global bin`

# Ensure path arrays do not contain duplicates.
typeset -gU cdpath fpath mailpath path

#
# Less
#

# Set the default Less options.
# Mouse-wheel scrolling has been disabled by -X (disable screen clearing).
# Remove -X and -F (exit if the content fits on one screen) to enable it.
export LESS='-F -g -i -M -R -S -w -X -z-4'

# Set the Less input preprocessor.
# Try both `lesspipe` and `lesspipe.sh` as either might exist on a system.
if (( $#commands[(i)lesspipe(|.sh)] )); then
  export LESSOPEN="| /usr/bin/env $commands[(i)lesspipe(|.sh)] %s 2>&-"
fi

#
# Temporary Files
#

if [[ ! -d "$TMPDIR" ]]; then
  export TMPDIR="$(mktemp -d)"
fi

TMPPREFIX="${TMPDIR%/}/zsh"

