#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Env for Prezto
ZSH_AUTOSUGGEST_USE_ASYNC=true

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
source ~/.zplug/init.zsh

# Plugins
zplug 'zplug/zplug', hook-build:'zplug --self-manage'
zplug "denysdovhan/spaceship-zsh-theme", use:spaceship.zsh, from:github, as:theme
zplug "oz/safe-paste"
zplug "jreese/zsh-titles"
zplug "hlissner/zsh-autopair", defer:2

# Install plugins if there are plugins that have not been installed
if ! zplug check; then
  zplug install
fi

# Then, source plugins and add commands to $PATH
#zplug load --verbose
zplug load
#clear

# Customize to your needs...

alias _resource-zsh='source ~/.zshrc'
alias _resource-tmux='tmux source ~/.tmux.conf'

alias top='htop'
alias cal='cal -m -n 3'

alias vim='nvim'
alias ls='lsd --group-dirs=first'
alias la='lsd -al --group-dirs=first'
alias gco='git checkout'
alias gcob='git checkout -b'
alias gcommit='git commit -am'
alias gfix='git add . && git fix'
alias gfeat='git add . && git feat'
alias gdocs='git add . && git docs'
alias gchore='git add . && git chore'
alias grefact='git add . && git refact'
alias gstyle='git add . && git style'
alias gtest='git add . && git test'
alias gpush='git push origin'
alias gpull='git pull --no-ff origin'
alias gbuild='git add . && git build'
alias glog='git log --pretty=short'
alias gfetchco='git-fetch-then-checkout'
alias gsync='git-sync'
alias grsorigin='git-reset-origin'

alias cmodx='sudo chmod +x '
alias cmod600='sudo chmod 600'
alias cmod700='sudo chmod 700'
alias cmod777='sudo chmod 777'
alias cmod744='sudo chmod 744'
alias cmod766='sudo chmod 766'
alias cmod644='sudo chmod 644'

expand-or-complete-with-dots() {      # This bunch of code displays red dots when autocompleting
  echo -n "\e[31m..\e[0m"         # a command with the tab key, "Oh-my-zsh"-style.
  zle expand-or-complete
  zle redisplay
}

zle -N expand-or-complete-with-dots
bindkey "^I" expand-or-complete-with-dots


SPACESHIP_BATTERY_SHOW=false
SPACESHIP_EXIT_CODE_SHOW=true

[ -s "/usr/local/opt/nvm/nvm.sh" ] && . "/usr/local/opt/nvm/nvm.sh"  # This loads nvm
[ -s "/usr/local/opt/nvm/etc/bash_completion" ] && . "/usr/local/opt/nvm/etc/bash_completion"  # This loads nvm bash_completion

eval "$(rbenv init -)"

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

eval "$(jump shell)"

source ~/.iterm2_shell_integration.zsh

